language: python
python:
- 3.5
install:
- pip install -r requirements.txt
- pip install -r test-requirements.txt
script:
- flake8 .
- 'python script.py'
notifications:
  email:
    - mcastelluccio@mozilla.com
    - release-mgmt@mozilla.com
